config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes

  root "recipes#index"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    has_attached_file :image, styles: {large: "600x600>", medium: "300x300> ", thumb: "150x150#"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
   # belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 5, maximum: 300}
  #  validates :user_id, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit, :update, :destroy]
    def index
        @recipe = Recipe.all
    end


    def show
        find_recipe

    end


    def new
        @recipe = Recipe.new

    end


    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            flash[:notice] = "Successfully created new recipe"
            redirect_to recipe_path(@recipe)
        else 
            render 'new'
        end
    end


    def update
        @recipe = find_recipe
            if @recipe.update(recipe_params)
                flash[:sucess] = " you have sucessfully updeated"
            redirect_to recipe_path(@recipe)
            
        else 
            render 'edit'
        end 

    end

    def edit
        find_recipe

    end

    def destroy
        @recipe = find_recipe.destroy        
         flash[:sucess] = "recipe is deleted"
           redirect_to recipes_path
        
    end


    private

    def recipe_params
        params.require(:recipe).permit(:title, :description, :image) 
    end
    def find_recipe
        @recipe = Recipe.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
      <ul>
        <li> <%= msg %> </li>
      </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sauerteighotel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>  
</html>

app/views/recipes/_form.html.erb
  <% if @recipe.errors.any?  %>  
  <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
      <% end %>
  </ul>
  <% end %>

  <%=form_for @recipe, html: {multipart: true} do |new| %>
  <p>
    <%= new.label :image %> <br/>
    <%= new.file_field :image %>
  </p>
  <p>
  <p>
    <%= new.label :title %> <br/>
    <%= new.text_field :title %>
  </p>
  <p>
  <%= new.label :description %><br/>
  <%= new.text_area :description %> 
  </p>
  <p>
  <%= new.submit %>
  
 </p>
  <% end %>

app/views/recipes/edit.html.erb
<h1>Edit page <h1>

<%= render 'form'%>

app/views/recipes/index.html.erb
<h1 >All recipe <h1>

<table>
         <%= link_to 'create new recipe', new_recipe_path%> 
    <tr>
        <th> Title </th>
        <th> Title </th>
    </tr>

    <% @recipe.each do |recipe|%>
    <tr>
        <td> <%= recipe.title%> </td>
        <td> <%= recipe.description%> </td>
        <td> <%= link_to 'show', recipe_path(recipe)%> </td>
        <td> <%= link_to 'Edit', edit_recipe_path(recipe)%> </td>
        <td> <%= link_to 'Delete', recipe_path(recipe), method: :delete, data:{confirm: "are you sure?"}%> </td>

 </tr> 
     <% end %>



    </tr>    

app/views/recipes/new.html.erb
<h1>new page <h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1 > show page<h1>

<p>

    Title: <%= @recipe.title %>

</p>


<p>

    Description: <%= @recipe.description %>

</p>